services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8005"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: sh -c "npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend_data:


networks:
  app-network:
    driver: bridge
